version: 2
models:
  - name: dim_airport
    description: "dim_airport"
    columns:
      - name: airport_code
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

models:
  - name: dim_aircraft
    description: "aircraft_data,seats"
    columns:
      - name: aircraft_code
        description: "The primary key for this table"
        tests:
          - unique
          - not_null


